import { useState, useEffect } from 'react';
import Footer from "@/components/organisms/Footer";
import Navbar from "@/components/organisms/Navbar";
import Home from "@/components/templates/Home";
import Head from "next/head";
import TextoAnimadoTemplate from '@/components/templates/TextoAnimadoTemplate';

export default function Index() {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setIsLoading(false);
    }, 5000);

    return () => clearTimeout(timer);
  }, [])

  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/maletin.svg" />
      </Head>
      {isLoading ? (
        <TextoAnimadoTemplate/>
      ) : (
        <>
         <Navbar/>
         <Home/>
         <Footer/>
        </>
      )}

    </>
  );
};
