import Home from "@/components/templates/Home";
import Head from "next/head";

export default function Index() {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/maletin.svg" />
      </Head>

      <Home/>
    </>
  );
};
