import Footer from "@/components/organisms/Footer";
import Navbar from "@/components/organisms/Navbar"
import Projects from "@/components/templates/Proyects"
import Head from "next/head";


const proyectsPage = () => {

  return (
    <>
     <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/maletin.svg" />
     </Head>

     <Navbar/>
     <Projects/>
     <Footer/>
    </>
  );
};

export default proyectsPage;
