import TextoAnimado from "@/components/molecules/TextoAnimado"
import Footer from "@/components/organisms/Footer";
import Navbar from "@/components/organisms/Navbar"
import Projects from "@/components/templates/Proyects"
import Head from "next/head";


const proyectsPage = () => {
  const secciones = [
    {
      titulo: "Bienvenido a mi portafolio",
      contenido: "Soy un Desarrollador Web Full Stack en formación y Enfermero Profesional. Mi objetivo es aplicar mis habilidades tanto en el desarrollo web como en diversos sectores, buscando siempre crear soluciones digitales innovadoras que resuelvan problemas de cualquier área, desde la salud hasta desafíos empresariales. Estoy comprometido con el aprendizaje continuo y con aportar valor a las empresas utilizando tecnología avanzada."
    }
  ];
  return (
    <>
     <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/maletin.svg" />
     </Head>

     <Navbar/>
     <TextoAnimado secciones={secciones}/>
     <Projects/>
     <Footer/>
    </>
  );
};

export default proyectsPage;
